---
output: github_document
---

# presentation prompts

Complete the prompts before the start of class on the day of the presentation. 

- These points guide the small-group discussions. 
- Much of this work will be part of your portfolio critiques. 

Once you decide the type of graph to be used for a display, you may replace the heading, for example, if you use a box plot for Display D1, you can change the heading from 

    ## D1 distributions 

to 

    ## D1 box plot


## D1 distributions 

State the number of observations:  

List the variables: 

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc 

State the graph type: 

Explain why the graph type is suited to the data structure:  

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc






## D2 multiway 

State the number of observations:  

List the variables: 

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc 

State the graph type: 

Explain why the graph type is suited to the data structure:  

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc




## D3 correlations 

State the number of observations:  

List the variables: 

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc 

State the graph type: 

Explain why the graph type is suited to the data structure:  

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc




## D4 injuries or fatalities displayed ethically  

**Context** 

Type of injury or fatality: 

People affected: 

Over what span of time: 



**Graph the data conventionally**

- If you are redesigning someone else's graph, include an image of the original 
- If not, graph the data yourself using a graph type suited to the data  

State the number of observations:  

List the variables: 

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc 

State the graph type: 

Explain why the graph type is suited to the data structure: 

- point 1 
- point 2 
- etc 

Explain the visual-rhetoric features of the graph that make it unethical:  

- point 
- point 
- etc

**Redesign the graph to display the data ethically**

State the new graph type (if any): 

Explain each design choice in the redesign and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Any suggestions on improving the ethical display of injuries or fatalities? 
- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc








## D5 redesign a graphical lie 

**The original deceptive graph**

The original image is included in the portfolio: Yes / No  

Explain the visual-rhetoric features of the graph that make it deceptive:  

- point 
- point 
- etc 

Comments from peers 

- Are there additional deceptive practices that have not been mentioned? 
- Other comments 
- etc




**The redesigned graph**

State the number of observations:  

Identify the variables:  

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc 

State the graph type: 

Explain why the graph type is suited to the data structure: 

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc











## D6 multivariate 

State the number of observations:  

List the variables: 

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc 

State the graph type: 

Explain why the graph type is suited to the data structure:  

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc





## D7 self-taught  

State the number of observations:  

List the variables: 

- quantitative var 1 
- quantitative var 2 
- etc 
- categorical var 1 and its levels 
- categorical var 1 and its levels 
- etc  

State the graph type: 

Explain why the graph type is suited to the data structure:  

- point 1 
- point 2 
- etc 

Explain each design choice and cite its supporting reference 

- choice, reference 
- choice, reference 
- etc 

Comments from peers 

- Does the data structure satisfy the portfolio display requirements?  
- From the Doumont paper, what type of story is being told? 
- Is the graph type suited to the data structure? 
- Other suggestion 
- etc




