---
output: github_document
---

<br>
Copy and paste the following raw Rmd script into your own Rmd file

## week 8 reading prompts  

Kostelnick, Charles (2007) The visual rhetoric of data displays: The conundrum
of clarity. *IEEE Transactions on Professional Communication* 50(2): 280--294.

**Prompt:** In your own words, summarize what the author means 
by the *rhetoric of science.*

**Response:** 




**Prompt:** In your own words, summarize what the author means 
by the *rhetoric of adaptation*

**Response:**  




**Prompt:** In your own words, summarize what the author means 
by *social rhetoric.*

**Response:** 




**Prompt:** In your own words, summarize what the author means 
by the *rhetoric of participation.*

**Response:** 




## reflection 

Respond to these last two prompts after our class discussion.

**Prompt:** Describe the idea from our discussion that is most important to you
or had the greatest impact on your thinking.   

**Response:** 




**Prompt:** Explain the idea from our discussion or the paper that you will 
apply to one of your data displays. Be specific: What display? What changes 
will you make? On what basis in the reading do you make the change? 

**Response:** 



