---
output: github_document
---


## instructions

If you know how to use an R Markdown script, copy and paste the script below into a new Rmd file and respond to the prompts before the due date. 


If not, just copy and paste the text below into a Word document for now and respond to the prompts before the due date. You can transfer it to an Rmd script once we have introduced the topic in class. 


## week 2 reading prompts  

Tufte, Edward (1997) The decision to launch the space shuttle Challenger. 
In: *Visual and statistical thinking: Displays of evidence for making
decisions.* Cheshire, CT: Graphics Press, 16--31.

**Prompt:** Tufte says, "Regardless of the indirect cultural causes of the
accident, there was a clear proximate cause." Summarize Tufte's explanation 
of the proximate cause.  

**Response:** 


**Prompt:** Describe the evidence the author presents to support those ideas.

**Response:**  


**Prompt:** What data were used in making the decision to launch? What data 
were not used but should have been used (according to Tufte) in making the
launch decision?

**Response:** 


**Prompt:** On page 23, Tufte presents a graph that provides visual evidence
that the "launch was completely outside the engineering database accumulated 
in 24 previous flight." Describe the structure of this data set:

- Number of observations 
- Data structure: classify each variable as quantitative (continuous or discrete) and categorical (nominal or ordinal and number of levels). 

**Response:**  


**Prompt:** Summarize the main thesis of the paper.  

**Response:** 


