suppressPackageStartupMessages(library(grid))# for textGrob()
suppressPackageStartupMessages(library(lattice))
suppressPackageStartupMessages(library(latticeExtra))
suppressPackageStartupMessages(library(plyr))
suppressPackageStartupMessages(library(RColorBrewer))
suppressPackageStartupMessages(library(reshape2))
suppressPackageStartupMessages(require(stringr))
suppressPackageStartupMessages(library(xtable))
suppressPackageStartupMessages(library(XLConnect))
